/* ============================================================
   PEDIATRIA — medicações com dose por quilo e faixa etária

   Cada item traz:
     apres      apresentação de referência (o que muda o volume)
     via
     idade      texto curto de quando pode
     minMeses   idade mínima em meses (null = qualquer idade); usada no filtro
     veto       { meses, txt } — abaixo dessa idade é CONTRAINDICADO, não
                apenas "sem dados". É o que pinta o cartão de vermelho.
     doses[]    { rot, mgkg, mgkgMax, freq, maxMg, conc, unid, nota }
                conc = mg por mL da apresentação; o app faz
                  mg/dose = peso × mgkg  (limitado a maxMg)
                  mL/dose = mg/dose ÷ conc
                conc null = comprimido ou dose fixa, só mostra mg.

   Doses de referência para pronto-socorro pediátrico. A apresentação
   varia por fabricante: confira a concentração do frasco antes de
   prescrever o volume.
   ============================================================ */

const FERR_PEDIA_GRUPOS = [
  { id:'analgesia', nome:'Analgesia e antitérmico', icone:'comprim' },
  { id:'antiemetico',nome:'Antieméticos',           icone:'estomago' },
  { id:'cortico',   nome:'Corticoides',             icone:'frasco' },
  { id:'inalacao',  nome:'Broncodilatador e inalação', icone:'pulmao' },
  { id:'atb-oral',  nome:'Antibiótico oral',        icone:'micro' },
  { id:'atb-ev',    nome:'Antibiótico parenteral',  icone:'soro' },
  { id:'alergia',   nome:'Anti-histamínico',        icone:'curativo' },
  { id:'emergencia',nome:'Emergência',              icone:'perigo' },
  { id:'digestivo', nome:'Hidratação e digestivo',  icone:'gota' },
  { id:'antiviral', nome:'Antiviral',               icone:'virus' },
  { id:'antiparasitario', nome:'Antiparasitários',  icone:'virus' }
];

/* medicações que NÃO se usa abaixo de certa idade — painel próprio */
const FERR_PEDIA_VETOS = [
  { nome:'Codeína e tramadol', faixa:'Menores de 12 anos',
    txt:'Metabolização imprevisível: risco de depressão respiratória fatal. Também contraindicados até os 18 anos após amigdalectomia ou adenoidectomia, e na criança obesa ou com apneia do sono.' },
  { nome:'Prometazina', faixa:'Menores de 2 anos',
    txt:'Depressão respiratória fatal descrita nessa faixa. Acima de 2 anos, usar a menor dose eficaz.' },
  { nome:'Ácido acetilsalicílico', faixa:'Qualquer idade em quadro viral',
    txt:'Síndrome de Reye. Não usar em suspeita de influenza, varicela ou virose febril. Exceção: doença de Kawasaki e indicação cardiológica formal.' },
  { nome:'Antitussígeno e descongestionante', faixa:'Menores de 6 anos',
    txt:'Sem benefício demonstrado e com relatos de evento grave. Especialmente proibido abaixo de 2 anos.' },
  { nome:'Descongestionante nasal tópico (nafazolina, oximetazolina)', faixa:'Menores de 2 anos; nafazolina, menores de 12 anos',
    txt:'Intoxicação por imidazolina é comum no Brasil: sonolência, bradicardia, hipotermia e apneia com poucas gotas. A bula da nafazolina contraindica abaixo de 12 anos.' },
  { nome:'Nimesulida', faixa:'Menores de 12 anos',
    txt:'Contraindicada pela bula (Anvisa): hepatotoxicidade e casos compatíveis com síndrome de Reye.' },
  { nome:'Escopolamina + dipirona, cetoprofeno e diclofenaco em gotas', faixa:'Menores de 1 ano',
    txt:'Fora da faixa da bula. Abaixo de 1 ano, use paracetamol; dipirona isolada a partir de 3 meses.' },
  { nome:'Sulfametoxazol-trimetoprima', faixa:'Menores de 2 meses',
    txt:'Risco de kernicterus por deslocamento da bilirrubina.' },
  { nome:'Ceftriaxona', faixa:'Recém-nascido ictérico, ou recebendo cálcio EV',
    txt:'Desloca bilirrubina e precipita com cálcio. No neonato, prefira cefotaxima.' },
  { nome:'Nitrofurantoína', faixa:'Menores de 1 mês',
    txt:'Risco de anemia hemolítica pela imaturidade enzimática.' },
  { nome:'Metoclopramida', faixa:'Menores de 1 ano',
    txt:'Alto risco de reação extrapiramidal. Entre 1 e 18 anos, só como segunda linha e por tempo curto.' },
  { nome:'Doxiciclina e tetraciclina', faixa:'Menores de 8 anos, em uso prolongado',
    txt:'Manchamento dentário permanente. Curso curto de doxiciclina é aceito em riquetsiose, onde o risco da doença supera o estético.' },
  { nome:'Quinolonas', faixa:'Menores de 18 anos, como rotina',
    txt:'Toxicidade em cartilagem e tendão. Reservadas a situações sem alternativa, com indicação formal. Exceção aceita: disenteria (ciprofloxacino por 3 dias, Ministério da Saúde e OMS).' },
  { nome:'Loperamida', faixa:'Menores de 6 anos',
    txt:'Risco de íleo paralítico, distensão e depressão do sistema nervoso central. Não usar em diarreia com sangue ou febre em nenhuma idade.' },
  { nome:'Ibuprofeno e demais anti-inflamatórios', faixa:'Menores de 6 meses',
    txt:'Também evitar em qualquer idade se houver desidratação, sangramento, varicela ou suspeita de dengue.' },
  { nome:'Dipirona', faixa:'Menores de 3 meses ou abaixo de 5 kg',
    txt:'Fora da faixa da bula. Abaixo disso, use paracetamol.' },
  { nome:'Benzocaína tópica', faixa:'Menores de 2 anos',
    txt:'Risco de metemoglobinemia. Não use gel de dentição com benzocaína.' },
  { nome:'Mel', faixa:'Menores de 1 ano',
    txt:'Botulismo do lactente. Vale para xarope caseiro e chupeta com mel.' }
];

const FERR_PEDIA = [

/* ---------------- ANALGESIA E ANTITÉRMICO ---------------- */
{ id:'p-paracetamol', grupo:'analgesia', nome:'Paracetamol', apres:'Gotas 200 mg/mL', via:'VO',
  idade:'Qualquer idade, inclusive recém-nascido', minMeses:0, veto:null,
  doses:[{ rot:'Dor e febre', mgkg:10, mgkgMax:15, freq:'6/6 h', maxMg:750, conc:200, unid:'mL',
           nota:'Máximo de 75 mg/kg/dia e de 4 g/dia. Tylenol 200 mg/mL: 15 gotas/mL, cerca de 13 a 14 mg por gota; regra da bula: 1 gota/kg por dose, máximo de 35 gotas. Genéricos podem ter outro gotejador — confira o rótulo.' }],
  atencao:'O antitérmico mais seguro no lactente pequeno. Some as doses de outras apresentações antes de repetir.',
  obs:['Início em 30 a 60 min, pico em 1 a 2 h.','Hepatotoxicidade é dose-dependente: cheque se a família já deu em casa.'] },

{ id:'p-dipirona', grupo:'analgesia', nome:'Dipirona', apres:'Gotas 500 mg/mL', via:'VO',
  idade:'A partir de 3 meses ou 5 kg', minMeses:3,
  veto:{ meses:3, txt:'Abaixo de 3 meses ou 5 kg está fora da faixa da bula — use paracetamol.' },
  doses:[{ rot:'Dor e febre', mgkg:10, mgkgMax:15, freq:'6/6 h', maxMg:1000, conc:500, unid:'mL',
           nota:'Gotas 500 mg/mL: 1 gota = 25 mg. Regra de bolso: 1 gota a cada 2 kg (cerca de 12,5 mg/kg), máximo de 40 gotas (1 g) por dose.' }],
  atencao:'Antitérmico de escolha quando o paracetamol não bastou. Agranulocitose é rara mas existe.',
  obs:['Apresentação EV 500 mg/mL: mesma dose por quilo, diluída e infundida lentamente.'] },

{ id:'p-ibuprofeno', grupo:'analgesia', nome:'Ibuprofeno', apres:'Gotas 50 mg/mL ou 100 mg/mL', via:'VO',
  idade:'A partir de 6 meses', minMeses:6,
  veto:{ meses:6, txt:'Não usar abaixo de 6 meses. Em qualquer idade, evite se houver desidratação, sangramento, varicela ou suspeita de dengue.' },
  alt:[[50,'Gotas 50 mg/mL'],[100,'Gotas 100 mg/mL']],
  doses:[{ rot:'Dor e febre', mgkg:5, mgkgMax:10, freq:'6/6 a 8/8 h', maxMg:400, conc:50, unid:'mL',
           nota:'Cálculo pela apresentação de 50 mg/mL. Se o frasco for 100 mg/mL, o volume é a metade. Máximo de 400 mg por dose e de 40 mg/kg/dia.' }],
  atencao:'Confira sempre a concentração do frasco: existem duas, e a troca dobra ou reduz pela metade a dose.',
  obs:['Melhor que o paracetamol para dor com inflamação.','Sempre com alimento; nunca no desidratado.'] },

{ id:'p-morfina', grupo:'analgesia', nome:'Morfina', apres:'Ampola 10 mg/mL', via:'EV',
  idade:'Qualquer idade, com monitorização', minMeses:0, veto:null,
  alt:[[1,'Diluída 1 mg/mL'],[10,'Ampola pura 10 mg/mL']],
  doses:[{ rot:'Dor intensa', mgkg:0.05, mgkgMax:0.1, freq:'4/4 h ou conforme dor', maxMg:5, conc:1, unid:'mL',
           nota:'Diluir 1 mL da ampola (10 mg) em 9 mL de água destilada = 1 mg/mL. O volume calculado usa essa diluição.' }],
  atencao:'Monitorize saturação e frequência respiratória. Tenha naloxona ao alcance.',
  obs:['Titule: comece na dose menor e repita conforme a resposta.'] },

{ id:'p-fentanil', grupo:'analgesia', nome:'Fentanila', apres:'Ampola 50 mcg/mL', via:'EV ou intranasal',
  idade:'Qualquer idade, com monitorização', minMeses:0, veto:null,
  doses:[{ rot:'Dor intensa — EV', mgkg:0.001, mgkgMax:0.002, freq:'conforme dor', maxMg:0.1, conc:0.05, unid:'mL',
           nota:'1 mcg/kg = 0,001 mg/kg. Infundir lentamente: em bolus rápido causa rigidez torácica.' },
         { rot:'Intranasal', mgkg:0.0015, mgkgMax:0.002, freq:'dose única', maxMg:0.1, conc:0.05, unid:'mL',
           nota:'Metade do volume em cada narina. Útil quando ainda não há acesso venoso.' }],
  atencao:'Rigidez torácica em bolus rápido. Depressão respiratória dose-dependente.',
  obs:[] },

/* ---------------- ANTIEMÉTICOS ---------------- */
{ id:'p-ondansetrona', grupo:'antiemetico', nome:'Ondansetrona', apres:'Ampola 2 mg/mL · comprimido 4 mg', via:'EV ou VO',
  idade:'A partir de 6 meses ou 8 kg na gastroenterite (abaixo disso, sem dados — não é contraindicação)', minMeses:0, veto:null,
  doses:[{ rot:'Vômito na gastroenterite', mgkg:0.15, mgkgMax:0.15, freq:'8/8 h se necessário', maxMg:4, conc:2, unid:'mL',
           nota:'0,15 mg/kg, máximo de 4 mg por dose. Dose única costuma bastar para permitir a reidratação oral. A ampola serve por via oral.' }],
  atencao:'Prolonga o intervalo QT. Cuidado se houver cardiopatia, distúrbio eletrolítico ou outra droga que alargue o QT.',
  obs:['O antiemético de escolha em pediatria: permite reidratação oral e evita internação.'] },

{ id:'p-dimenidrinato', grupo:'antiemetico', nome:'Dimenidrinato + B6', apres:'Gotas 25 mg/mL', via:'VO',
  idade:'A partir de 2 anos', minMeses:24,
  veto:{ meses:24, txt:'Não recomendado abaixo de 2 anos — sedação e risco de reação paradoxal.' },
  doses:[{ rot:'Náusea e cinetose', mgkg:1.25, mgkgMax:1.25, freq:'6/6 a 8/8 h', maxMg:25, conc:25, unid:'mL',
           nota:'Máximo de 75 mg/dia dos 2 aos 6 anos, e de 150 mg/dia dos 6 aos 12.' }],
  atencao:'Seda. Não é a primeira escolha para vômito de gastroenterite — a ondansetrona é melhor.',
  obs:[] },

{ id:'p-metoclopramida', grupo:'antiemetico', nome:'Metoclopramida', apres:'Ampola 5 mg/mL · gotas 4 mg/mL', via:'EV ou VO',
  idade:'A partir de 1 ano, e só como segunda linha', minMeses:12,
  veto:{ meses:12, txt:'CONTRAINDICADA abaixo de 1 ano — alto risco de reação extrapiramidal. De 1 a 18 anos, apenas segunda linha e por até 5 dias.' },
  alt:[[5,'Ampola 5 mg/mL'],[4,'Gotas 4 mg/mL']],
  doses:[{ rot:'Náusea refratária', mgkg:0.1, mgkgMax:0.15, freq:'8/8 h', maxMg:10, conc:5, unid:'mL',
           nota:'Máximo de 0,5 mg/kg/dia e de 5 dias de uso.' }],
  atencao:'Distonia aguda é frequente na criança. Se ocorrer, o tratamento é biperideno ou difenidramina.',
  obs:['Prefira ondansetrona sempre que disponível.'] },

/* ---------------- CORTICOIDES ---------------- */
{ id:'p-prednisolona', grupo:'cortico', nome:'Prednisolona', apres:'Solução 3 mg/mL', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  alt:[[3,'Solução 3 mg/mL'],[1,'Solução 1 mg/mL']],
  doses:[{ rot:'Asma e alergia', mgkg:1, mgkgMax:2, freq:'1× ao dia, 3 a 5 dias', maxMg:40, conc:3, unid:'mL',
           nota:'Teto por idade (GINA): 20 mg abaixo de 2 anos, 30 mg de 2 a 5 anos, 40 mg acima de 5 anos. O cálculo limita só a 40 mg. Curso curto não precisa de desmame. Dar pela manhã.' }],
  atencao:'Teto menor na criança pequena: 20 mg abaixo de 2 anos e 30 mg de 2 a 5 anos. Existe também solução de 1 mg/mL: confira o frasco antes de converter em volume.',
  obs:['Na crise de asma, o corticoide precoce reduz internação.'] },

{ id:'p-dexametasona', grupo:'cortico', nome:'Dexametasona', apres:'Ampola 4 mg/mL · elixir 0,5 mg/5 mL', via:'VO, IM ou EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  alt:[[4,'Ampola 4 mg/mL'],[0.1,'Elixir 0,1 mg/mL']],
  doses:[{ rot:'Crupe (laringite)', mgkg:0.15, mgkgMax:0.6, freq:'dose única', maxMg:10, conc:4, unid:'mL',
           nota:'Dose única resolve a maioria dos casos leves e moderados. A via oral funciona tão bem quanto a IM (a ampola pode ser dada por boca, misturada a suco).' },
         { rot:'Asma — alternativa ao corticoide oral', mgkg:0.6, mgkgMax:0.6, freq:'1 a 2 doses', maxMg:16, conc:4, unid:'mL',
           nota:'Uma ou duas doses substituem 5 dias de prednisolona, com adesão melhor.' }],
  atencao:'No crupe, dê o corticoide mesmo no caso leve — muda a evolução.',
  obs:[] },

{ id:'p-hidrocortisona', grupo:'cortico', nome:'Hidrocortisona', apres:'Frasco-ampola 100 e 500 mg', via:'EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Asma grave e anafilaxia', mgkg:4, mgkgMax:4, freq:'6/6 h', maxMg:100, conc:null, unid:'mg',
           nota:'4 mg/kg por dose, máximo de 100 mg, de 6/6 h. Reconstituir conforme o frasco. Adjuvante: na anafilaxia, não substitui a adrenalina.' }],
  atencao:'Na anafilaxia o corticoide não trata a fase aguda — a adrenalina IM é que trata.',
  obs:[] },

/* ---------------- BRONCODILATADOR E INALAÇÃO ---------------- */
{ id:'p-salbutamol-spray', grupo:'inalacao', nome:'Salbutamol spray', apres:'100 mcg por jato', via:'Inalatória com espaçador',
  idade:'Qualquer idade, sempre com espaçador', minMeses:0, veto:null,
  doses:[{ rot:'Crise leve a moderada', mgkg:null, fixa:'2 a 6 jatos', freq:'a cada 20 min na 1ª hora', conc:null, unid:'jatos',
           nota:'Regra prática: 1 jato para cada 2 a 3 kg, mínimo 2 e máximo 10 jatos. Um jato de cada vez, com 4 a 6 respirações entre eles.' },
         { rot:'Crise grave', mgkg:null, fixa:'6 a 10 jatos', freq:'a cada 20 min na 1ª hora', conc:null, unid:'jatos',
           nota:'Espaçador com máscara abaixo de 4 anos; com bocal acima disso.' }],
  atencao:'Spray com espaçador é tão eficaz quanto nebulização e causa menos taquicardia. Prefira.',
  obs:['Sem espaçador, quase nada do jato chega ao pulmão da criança.'] },

{ id:'p-salbutamol-neb', grupo:'inalacao', nome:'Salbutamol gotas', apres:'Solução 5 mg/mL (1 gota = 0,25 mg)', via:'Nebulização',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Nebulização', mgkg:0.15, mgkgMax:0.15, freq:'a cada 20 min na 1ª hora', maxMg:5, conc:5, unid:'mL',
           nota:'0,15 mg/kg, mínimo de 2,5 mg (0,5 mL = 10 gotas) e máximo de 5 mg (1 mL = 20 gotas). 1 gota = 0,25 mg. Abaixo de 17 kg, use o mínimo de 10 gotas. Diluir em 3 a 5 mL de soro fisiológico.' }],
  atencao:'Abaixo de 17 kg o cálculo fica abaixo do mínimo: dê 2,5 mg (10 gotas). Causa tremor, taquicardia e hipocalemia; em uso repetido, cheque o potássio.',
  obs:[] },

{ id:'p-ipratropio', grupo:'inalacao', nome:'Ipratrópio gotas', apres:'Solução 0,25 mg/mL', via:'Nebulização',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Até 20 kg ou menor de 6 anos', mgkg:null, fixa:'20 gotas (250 mcg = 1 mL)', freq:'a cada 20 min na 1ª hora', conc:null, unid:'gotas',
           nota:'Associado ao salbutamol na mesma nebulização, nos 3 primeiros ciclos. 1 gota = 12,5 mcg.' },
         { rot:'Acima de 20 kg ou 6 anos ou mais', mgkg:null, fixa:'40 gotas (500 mcg = 2 mL)', freq:'a cada 20 min na 1ª hora', conc:null, unid:'gotas',
           nota:'O benefício é maior nas primeiras horas da crise moderada a grave.' }],
  atencao:'Proteja os olhos com a máscara bem ajustada: o contato causa midríase e visão borrada.',
  obs:[] },

{ id:'p-adrenalina-neb', grupo:'inalacao', nome:'Adrenalina para nebulização', apres:'Ampola 1 mg/mL (1:1000)', via:'Nebulização',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Crupe moderado a grave', mgkg:0.5, mgkgMax:0.5, freq:'repetir conforme resposta', maxMg:5, conc:1, unid:'mL',
           nota:'Completar com soro fisiológico até 5 mL. Efeito em 10 a 30 min e dura cerca de 2 h.' }],
  atencao:'Observe por pelo menos 2 h após a nebulização: o estridor pode voltar quando o efeito passa.',
  obs:['Sempre associada ao corticoide, nunca sozinha.'] },

/* ---------------- ANTIBIÓTICO ORAL ---------------- */
{ id:'p-amoxicilina', grupo:'atb-oral', nome:'Amoxicilina', apres:'Suspensão 250 mg/5 mL (50 mg/mL)', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  alt:[[50,'250 mg/5 mL'],[80,'400 mg/5 mL']],
  doses:[{ rot:'Dose habitual', mgkg:50, mgkgMax:50, freq:'dividido de 8/8 h', maxMg:1500, conc:50, unid:'mL',
           nota:'O valor mostrado é a dose do DIA — divida em 3 tomadas.' },
         { rot:'Dose alta (otite, pneumonia)', mgkg:80, mgkgMax:90, freq:'dividido de 12/12 h', maxMg:3000, conc:50, unid:'mL',
           nota:'Dose do dia, dividida em 2 tomadas. Indicada onde há pneumococo com resistência intermediária.' }],
  atencao:'Existe suspensão de 400 mg/5 mL (80 mg/mL): nesse frasco o volume é bem menor.',
  obs:['Primeira escolha em otite média aguda, sinusite e pneumonia típica.'] },

{ id:'p-amoxclav', grupo:'atb-oral', nome:'Amoxicilina + clavulanato', apres:'Suspensão 400/57 mg por 5 mL (80 mg/mL de amoxicilina)', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Dose por amoxicilina', mgkg:45, mgkgMax:90, freq:'dividido de 12/12 h', maxMg:2800, conc:80, unid:'mL',
           nota:'Dose do dia. Calcule sempre pelo componente amoxicilina, nunca pela soma dos dois.' },
         { rot:'Menor de 3 meses', mgkg:30, mgkgMax:30, freq:'dividido de 12/12 h', maxMg:null, conc:50, unid:'mL',
           nota:'30 mg/kg/dia de amoxicilina. Volume calculado para a suspensão 250/62,5 mg por 5 mL (50 mg/mL); a 400/57 não é indicada nessa idade.' }],
  atencao:'Abaixo de 3 meses o teto é 30 mg/kg/dia (rim imaturo). Diarreia é o efeito adverso mais comum e faz a família abandonar o tratamento — avise antes.',
  obs:['Reservada a falha da amoxicilina, otite recorrente, sinusite complicada e mordedura.'] },

{ id:'p-azitromicina', grupo:'atb-oral', nome:'Azitromicina', apres:'Suspensão 200 mg/5 mL (40 mg/mL)', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Dose diária', mgkg:10, mgkgMax:10, freq:'1× ao dia, 3 a 5 dias', maxMg:500, conc:40, unid:'mL',
           nota:'Otite: 10 mg/kg/dia por 3 dias, ou 10 mg/kg no 1º dia e 5 mg/kg do 2º ao 5º.' },
         { rot:'Faringite estreptocócica (alergia à penicilina)', mgkg:12, mgkgMax:12, freq:'1× ao dia, 5 dias', maxMg:500, conc:40, unid:'mL',
           nota:'12 mg/kg/dia por 5 dias, máximo de 500 mg/dia.' }],
  atencao:'Prolonga o QT. Não é primeira escolha para otite nem para pneumonia típica.',
  obs:['Escolha em coqueluche e em pneumonia atípica do escolar.'] },

{ id:'p-cefalexina', grupo:'atb-oral', nome:'Cefalexina', apres:'Suspensão 250 mg/5 mL (50 mg/mL)', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Dose diária', mgkg:50, mgkgMax:100, freq:'dividido de 6/6 h', maxMg:4000, conc:50, unid:'mL',
           nota:'Dose do dia, em 4 tomadas. A dose maior fica para infecção de pele mais extensa.' }],
  atencao:'Não cobre pneumococo resistente nem Haemophilus — não sirva para otite.',
  obs:['Boa escolha em impetigo, celulite simples e ITU baixa.'] },

{ id:'p-smztmp', grupo:'atb-oral', nome:'Sulfametoxazol + trimetoprima', apres:'Suspensão 200/40 mg por 5 mL (8 mg/mL de trimetoprima)', via:'VO',
  idade:'A partir de 2 meses', minMeses:2,
  veto:{ meses:2, txt:'CONTRAINDICADO abaixo de 2 meses — desloca a bilirrubina e pode causar kernicterus.' },
  doses:[{ rot:'Dose por trimetoprima', mgkg:8, mgkgMax:10, freq:'dividido de 12/12 h', maxMg:320, conc:8, unid:'mL',
           nota:'Dose do dia, calculada pelo trimetoprima. Divida em 2 tomadas.' }],
  atencao:'Resistência alta de E. coli em muitas regiões — confira o perfil local antes de usar em ITU.',
  obs:[] },

/* ---------------- ANTIBIÓTICO PARENTERAL ---------------- */
{ id:'p-ceftriaxona', grupo:'atb-ev', nome:'Ceftriaxona', apres:'Frasco 1 g', via:'EV ou IM',
  idade:'Evitar no recém-nascido', minMeses:1,
  veto:{ meses:1, txt:'Não usar no recém-nascido ictérico nem em quem recebe cálcio endovenoso — desloca bilirrubina e precipita com cálcio. No neonato, prefira cefotaxima.' },
  doses:[{ rot:'Dose habitual', mgkg:50, mgkgMax:75, freq:'1× ao dia', maxMg:2000, conc:null, unid:'mg',
           nota:'Dose do dia. Pode ser dose única diária.' },
         { rot:'Meningite', mgkg:100, mgkgMax:100, freq:'dividido de 12/12 h', maxMg:4000, conc:null, unid:'mg',
           nota:'Dose do dia. Nunca atrase a primeira dose esperando punção lombar ou tomografia.' }],
  atencao:'Não infundir junto com solução contendo cálcio, incluindo Ringer lactato.',
  obs:[] },

{ id:'p-penicilina-crist', grupo:'atb-ev', nome:'Penicilina cristalina', apres:'Frasco 5.000.000 UI', via:'EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Pneumonia', mgkg:150000, mgkgMax:200000, freq:'dividido de 6/6 h', maxMg:24000000, conc:null, unid:'UI',
           nota:'Dose do dia em UNIDADES, não em mg. Divida em 4 tomadas.' }],
  atencao:'Continua sendo a escolha na pneumonia pneumocócica internada.',
  obs:[] },

{ id:'p-oxacilina', grupo:'atb-ev', nome:'Oxacilina', apres:'Frasco 500 mg', via:'EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Dose diária', mgkg:100, mgkgMax:200, freq:'dividido de 6/6 h', maxMg:12000, conc:null, unid:'mg',
           nota:'Dose do dia. A dose maior fica para infecção grave e osteoarticular.' }],
  atencao:'Não cobre MRSA. Se houver suspeita, use vancomicina ou clindamicina.',
  obs:[] },

{ id:'p-gentamicina', grupo:'atb-ev', nome:'Gentamicina', apres:'Ampola 40 mg/mL', via:'EV ou IM',
  idade:'Qualquer idade, com ajuste no neonato', minMeses:0, veto:null,
  doses:[{ rot:'Dose diária única', mgkg:5, mgkgMax:7.5, freq:'1× ao dia', maxMg:400, conc:40, unid:'mL',
           nota:'Dose única diária é tão eficaz e menos nefrotóxica que a fracionada. No neonato o intervalo é maior.' }],
  atencao:'Nefrotóxica e ototóxica. Cheque a função renal e evite associar a outros nefrotóxicos.',
  obs:[] },

{ id:'p-clindamicina', grupo:'atb-ev', nome:'Clindamicina', apres:'Ampola 150 mg/mL', via:'EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Dose diária', mgkg:30, mgkgMax:40, freq:'dividido de 6/6 ou 8/8 h', maxMg:2700, conc:150, unid:'mL',
           nota:'Dose do dia. Cobre MRSA comunitário e anaeróbio.' }],
  atencao:'Risco de colite por C. difficile.',
  obs:[] },

/* ---------------- ANTI-HISTAMÍNICO ---------------- */
{ id:'p-dexclorfeniramina', grupo:'alergia', nome:'Dexclorfeniramina', apres:'Solução 0,4 mg/mL', via:'VO',
  idade:'A partir de 2 anos', minMeses:24,
  veto:{ meses:24, txt:'Não usar abaixo de 2 anos — sedação importante e risco de reação paradoxal.' },
  doses:[{ rot:'Prurido e urticária', mgkg:0.15, mgkgMax:0.15, freq:'dividido de 8/8 h', maxMg:6, conc:0.4, unid:'mL',
           nota:'Dose do dia, em 3 tomadas.' }],
  atencao:'Seda bastante. Na anafilaxia é apenas adjuvante: nunca substitui a adrenalina.',
  obs:[] },

{ id:'p-loratadina', grupo:'alergia', nome:'Loratadina', apres:'Xarope 1 mg/mL', via:'VO',
  idade:'A partir de 2 anos', minMeses:24,
  veto:{ meses:24, txt:'Não recomendada abaixo de 2 anos.' },
  doses:[{ rot:'2 a 5 anos, ou abaixo de 30 kg', mgkg:null, fixa:'5 mg (5 mL)', freq:'1× ao dia', conc:null, unid:'mL',
           nota:'Dose fixa por faixa, não por quilo.' },
         { rot:'Acima de 30 kg', mgkg:null, fixa:'10 mg (10 mL)', freq:'1× ao dia', conc:null, unid:'mL',
           nota:'Não seda, ao contrário da dexclorfeniramina.' }],
  atencao:'Preferível à dexclorfeniramina para uso diurno: não prejudica escola nem atenção.',
  obs:[] },

/* ---------------- EMERGÊNCIA ---------------- */
{ id:'p-adrenalina-im', grupo:'emergencia', nome:'Adrenalina IM — anafilaxia', apres:'Ampola 1 mg/mL (1:1000)', via:'IM na coxa',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Anafilaxia', mgkg:0.01, mgkgMax:0.01, freq:'repetir a cada 5 a 15 min', maxMg:0.5, conc:1, unid:'mL',
           nota:'Ampola pura, sem diluir. Vasto lateral da coxa. Não há contraindicação absoluta na anafilaxia.' }],
  atencao:'É o único tratamento que muda o desfecho. Corticoide e anti-histamínico são adjuvantes.',
  obs:['Repita se não houver melhora em 5 a 15 min.','Observe por 4 a 8 h pelo risco de reação bifásica.'] },

{ id:'p-adrenalina-pcr', grupo:'emergencia', nome:'Adrenalina EV/IO — parada', apres:'Diluir 1 mL de 1:1000 em 9 mL de água destilada = 1:10.000 (0,1 mg/mL)', via:'EV ou intraóssea',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Parada cardiorrespiratória', mgkg:0.01, mgkgMax:0.01, freq:'a cada 3 a 5 min', maxMg:1, conc:0.1, unid:'mL',
           nota:'O volume mostrado já considera a diluição 1:10.000 — equivale a 0,1 mL/kg. Flush de 5 mL depois.' }],
  atencao:'Confira a diluição antes de aspirar: a concentração errada aqui é fatal.',
  obs:[] },

{ id:'p-diazepam', grupo:'emergencia', nome:'Diazepam', apres:'Ampola 5 mg/mL', via:'EV ou retal',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Crise convulsiva — EV', mgkg:0.2, mgkgMax:0.3, freq:'repetir 1× após 5 min', maxMg:10, conc:5, unid:'mL',
           nota:'0,2 a 0,3 mg/kg, máximo de 10 mg por dose. Infundir lentamente. Prepare a via aérea antes.' },
         { rot:'Via retal (sem acesso)', mgkg:0.5, mgkgMax:0.5, freq:'dose única', maxMg:20, conc:5, unid:'mL',
           nota:'0,5 mg/kg, máximo de 20 mg. Aspirar a ampola e administrar com sonda curta no reto.' }],
  atencao:'Depressão respiratória é o efeito esperado, não a surpresa. Tenha bolsa-válvula-máscara pronta.',
  obs:[] },

{ id:'p-midazolam', grupo:'emergencia', nome:'Midazolam', apres:'Ampola 5 mg/mL', via:'IM, intranasal ou EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  alt:[[5,'Ampola 5 mg/mL'],[1,'Ampola 1 mg/mL']],
  doses:[{ rot:'Crise — IM ou intranasal', mgkg:0.2, mgkgMax:0.2, freq:'dose única', maxMg:10, conc:5, unid:'mL',
           nota:'Tão eficaz quanto o diazepam endovenoso e não exige acesso. Metade em cada narina, se intranasal.' },
         { rot:'Crise — EV', mgkg:0.1, mgkgMax:0.15, freq:'repetir 1× após 5 min', maxMg:10, conc:5, unid:'mL',
           nota:'Confira a concentração: existem apresentações de 1 mg/mL e de 5 mg/mL.' }],
  atencao:'Primeira escolha quando ainda não há acesso venoso.',
  obs:[] },

{ id:'p-fenitoina', grupo:'emergencia', nome:'Fenitoína', apres:'Ampola 50 mg/mL', via:'EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Estado de mal — ataque', mgkg:20, mgkgMax:20, freq:'dose de ataque', maxMg:1000, conc:50, unid:'mL',
           nota:'Diluir SOMENTE em soro fisiológico — precipita em glicose. Velocidade máxima de 1 mg/kg/min.' }],
  atencao:'Monitorize ritmo e pressão durante a infusão: causa hipotensão e arritmia se correr rápido.',
  obs:[] },

{ id:'p-glicose', grupo:'emergencia', nome:'Glicose 10%', apres:'Solução 100 mg/mL', via:'EV ou intraóssea',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Hipoglicemia', mgkg:200, mgkgMax:500, freq:'repetir conforme glicemia', maxMg:25000, conc:100, unid:'mL',
           nota:'Equivale a 2 a 5 mL/kg de glicose a 10%. Reavaliar a glicemia em 15 min.' }],
  atencao:'No lactente use glicose a 10%, nunca a 50% — a hipertônica lesa a veia e o cérebro.',
  obs:['Para obter 10% a partir da 50%: 1 volume de glicose 50% + 4 volumes de água destilada.'] },

{ id:'p-sf-bolus', grupo:'emergencia', nome:'Soro fisiológico em bolus', apres:'SF 0,9%', via:'EV ou intraóssea',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Choque e desidratação grave', mgkg:null, fixa:'20 mL/kg', freq:'reavaliar entre cada bolus', conc:null, unid:'mL',
           nota:'Use o cálculo de volume abaixo. Reavalie ausculta, fígado e perfusão entre as alíquotas.' },
         { rot:'Cardiopata ou desnutrido grave', mgkg:null, fixa:'5 a 10 mL/kg', freq:'reavaliar entre cada bolus', conc:null, unid:'mL',
           nota:'Nesses, 20 mL/kg pode precipitar congestão.' }],
  atencao:'Hepatomegalia e estertores que surgem durante a expansão significam parar o volume.',
  obs:[] },

/* ---------------- HIDRATAÇÃO E DIGESTIVO ---------------- */
{ id:'p-sro', grupo:'digestivo', nome:'Sais de reidratação oral', apres:'Sachê da OMS de osmolaridade reduzida', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Plano A — sem desidratação', mgkg:null, fixa:'Menor de 1 ano: 50 a 100 mL · 1 a 10 anos: 100 a 200 mL · acima de 10 anos: à vontade',
           freq:'após cada perda', conc:null, unid:'mL', nota:'Após cada evacuação ou vômito (Ministério da Saúde, 2023). Manter alimentação e aleitamento.' },
         { rot:'Plano B — desidratação leve a moderada', mgkg:75, mgkgMax:75, freq:'em 4 h, no serviço', maxMg:null, conc:1000, unid:'mL',
           nota:'75 mL/kg em 4 horas, em copo ou colher, sob supervisão. Reavaliar ao fim.' }],
  atencao:'A reidratação oral supervisionada resolve a maioria dos casos e evita punção venosa.',
  obs:['Vômito não contraindica: ofereça em pequenos volumes, e considere ondansetrona.'] },

{ id:'p-zinco', grupo:'digestivo', nome:'Zinco', apres:'Solução 4 mg/mL', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Menores de 6 meses', mgkg:null, fixa:'10 mg/dia', freq:'1× ao dia por 10 a 14 dias', conc:null, unid:'mg',
           nota:'Reduz duração e gravidade da diarreia, e a recorrência nos meses seguintes.' },
         { rot:'6 meses ou mais', mgkg:null, fixa:'20 mg/dia', freq:'1× ao dia por 10 a 14 dias', conc:null, unid:'mg',
           nota:'Recomendação da OMS e do Ministério da Saúde em toda diarreia aguda.' }],
  atencao:'Prescreva junto com o soro de reidratação: é a dupla recomendada, e costuma ser esquecida.',
  obs:[] },

{ id:'p-simeticona', grupo:'digestivo', nome:'Simeticona', apres:'Gotas 75 mg/mL', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Cólica do lactente', mgkg:null, fixa:'3 a 5 gotas', freq:'até 4× ao dia', conc:null, unid:'gotas',
           nota:'Não é absorvida. O benefício é modesto e boa parte é efeito do acolhimento.' }],
  atencao:'Cólica do lactente não tem tratamento medicamentoso eficaz. Oriente a família sobre o curso natural.',
  obs:[] },

/* ---------------- ACRÉSCIMOS DA REVISÃO (02/10/2026) ----------------
   Ids e índices de dose usados pelas receitas pediátricas: não reordene. */

{ id:'p-levetiracetam', grupo:'emergencia', nome:'Levetiracetam', apres:'Ampola 500 mg/5 mL (100 mg/mL) · solução oral 100 mg/mL', via:'EV ou VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Estado de mal — ataque EV', mgkg:60, mgkgMax:60, freq:'dose única em 10 a 15 min', maxMg:4500, conc:100, unid:'mL',
           nota:'60 mg/kg, máximo de 4.500 mg. Diluir em SF 0,9% ou SG 5%. Segunda linha após 2 doses de benzodiazepínico, com eficácia igual à da fenitoína e menos efeito colateral (ESETT).' },
         { rot:'Manutenção VO', mgkg:10, mgkgMax:30, freq:'12/12 h', maxMg:1500, conc:100, unid:'mL',
           nota:'Começar com 10 mg/kg por dose e subir conforme resposta, até 30 mg/kg por dose (máximo de 1.500 mg). Definir com a neurologia.' }],
  atencao:'Não precisa de monitorização cardíaca nem de veia exclusiva. Ajustar a dose na insuficiência renal.',
  obs:['Pode causar irritabilidade e alteração de comportamento.'] },

{ id:'p-sulfato-magnesio', grupo:'emergencia', nome:'Sulfato de magnésio', apres:'Ampola 50% (500 mg/mL) · 20% (200 mg/mL) · 10% (100 mg/mL)', via:'EV',
  idade:'Qualquer idade (na asma, a partir de 2 anos há mais dados)', minMeses:0, veto:null,
  alt:[[500,'Ampola 50%'],[200,'Ampola 20%'],[100,'Ampola 10%']],
  doses:[{ rot:'Asma grave refratária', mgkg:25, mgkgMax:50, freq:'dose única em 20 min', maxMg:2000, conc:500, unid:'mL',
           nota:'25 a 50 mg/kg, máximo de 2 g. O volume é da ampola escolhida: diluir em SF 0,9% (concentração final de até 20%) e infundir em 20 minutos.' }],
  atencao:'Confira a concentração da ampola: existem 10%, 20% e 50%. Monitorize pressão, reflexos e frequência respiratória; antídoto é o gluconato de cálcio.',
  obs:['Indicado na crise grave que não respondeu ao beta-2, ipratrópio e corticoide da primeira hora.'] },

{ id:'p-oseltamivir', grupo:'antiviral', nome:'Oseltamivir', apres:'Cápsulas 30, 45 e 75 mg · suspensão 12 mg/mL (manipulada ou preparada a partir da cápsula)', via:'VO',
  idade:'Qualquer idade, inclusive recém-nascido', minMeses:0, veto:null,
  alt:[[12,'Suspensão 12 mg/mL'],[15,'Cápsula 75 mg em 5 mL (15 mg/mL)']],
  doses:[{ rot:'Tratamento — 1 ano ou mais (faixa de peso)',
           porPeso:[{ min:0, max:15, txt:'30 mg (2,5 mL da suspensão 12 mg/mL)', rot:'até 15 kg' },
                    { min:15.01, max:23, txt:'45 mg (3,75 mL da suspensão 12 mg/mL)', rot:'15 a 23 kg' },
                    { min:23.01, max:40, txt:'60 mg (5 mL da suspensão 12 mg/mL)', rot:'23 a 40 kg' },
                    { min:40.01, max:999, txt:'75 mg (1 cápsula)', rot:'acima de 40 kg' }],
           regra:'Até 15 kg: 30 mg · 15 a 23 kg: 45 mg · 23 a 40 kg: 60 mg · acima de 40 kg: 75 mg',
           fixa:'Até 15 kg: 30 mg · 15 a 23 kg: 45 mg · 23 a 40 kg: 60 mg · acima de 40 kg: 75 mg', fora:'Informe o peso',
           freq:'12/12 h por 5 dias', nota:'Faixas válidas a partir de 1 ano. Abaixo de 1 ano, use a dose por quilo (linha seguinte).' },
         { rot:'Tratamento — menor de 1 ano', mgkg:3, mgkgMax:3.5, freq:'12/12 h por 5 dias', maxMg:null, conc:12, unid:'mL',
           nota:'0 a 8 meses: 3 mg/kg; 9 a 11 meses: 3,5 mg/kg (Ministério da Saúde, protocolo de influenza).' }],
  atencao:'Começar em até 48 h do início, mas na síndrome respiratória grave ou na criança de risco (menor de 5 anos, comorbidade) tratar mesmo depois disso, sem esperar exame.',
  obs:['Náusea e vômito são os efeitos mais comuns: dar com alimento.','Ajustar no clearance de creatinina abaixo de 30 mL/min.'] },

{ id:'p-aciclovir', grupo:'antiviral', nome:'Aciclovir', apres:'Suspensão 200 mg/5 mL (40 mg/mL) · frasco-ampola 250 mg', via:'VO ou EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'VO — varicela', mgkg:20, mgkgMax:20, freq:'6/6 h por 5 dias', maxMg:800, conc:40, unid:'mL',
           nota:'20 mg/kg por dose, 4 vezes ao dia (máximo de 800 mg por dose), começando em até 24 h do exantema. Gengivoestomatite herpética: 15 mg/kg 5 vezes ao dia (máximo de 200 mg) por 7 dias.' },
         { rot:'EV — herpes grave, encefalite, imunossuprimido', mgkg:10, mgkgMax:20, freq:'8/8 h', maxMg:1000, conc:null, unid:'mg',
           nota:'20 mg/kg de 8/8 h no recém-nascido e no lactente até 3 meses (herpes neonatal); 10 a 15 mg/kg acima disso. Infundir em 1 hora, bem diluído.' }],
  atencao:'Nefrotóxico por cristalização: mantenha a criança bem hidratada e ajuste pela função renal.',
  obs:['Na varicela da criança saudável, o benefício é modesto: indicar acima de 12 anos, em doença de pele ou pulmão crônica, uso de corticoide ou caso secundário domiciliar.'] },

{ id:'p-ampicilina', grupo:'atb-ev', nome:'Ampicilina', apres:'Frasco-ampola 500 mg e 1 g', via:'EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Dose habitual', mgkg:50, mgkgMax:50, freq:'6/6 h', maxMg:2000, conc:null, unid:'mg',
           nota:'50 mg/kg por dose, máximo de 2 g por dose.' },
         { rot:'Meningite e neonato com suspeita de meningite', mgkg:75, mgkgMax:100, freq:'6/6 h', maxMg:2000, conc:null, unid:'mg',
           nota:'Acima de 7 dias: 75 mg/kg de 6/6 h. Até 7 dias de vida: 100 mg/kg de 8/8 h. Criança maior: até 100 mg/kg de 6/6 h, máximo de 2 g por dose.' }],
  atencao:'No lactente febril pequeno, é o que cobre Listeria e enterococo: as cefalosporinas não cobrem.',
  obs:['Associar gentamicina ou cefotaxima no recém-nascido.'] },

{ id:'p-cefuroxima', grupo:'atb-oral', nome:'Cefuroxima', apres:'Suspensão 250 mg/5 mL (50 mg/mL) · comprimido 250 e 500 mg', via:'VO',
  idade:'A partir de 3 meses (bula)', minMeses:3, veto:null,
  doses:[{ rot:'Dose habitual', mgkg:15, mgkgMax:15, freq:'12/12 h', maxMg:500, conc:50, unid:'mL',
           nota:'15 mg/kg por dose, máximo de 500 mg, por 5 a 10 dias conforme a infecção.' }],
  atencao:'Dar com alimento: a absorção cai muito em jejum. Gosto amargo da suspensão atrapalha a adesão.',
  obs:['Opção em otite e sinusite na alergia não grave à penicilina, e na falha da amoxicilina.'] },

{ id:'p-budesonida-neb', grupo:'inalacao', nome:'Budesonida para nebulização', apres:'Suspensão 0,25 mg/mL e 0,5 mg/mL (flaconetes de 2 mL)', via:'Nebulização',
  idade:'A partir de 6 meses (bula)', minMeses:6, veto:null,
  doses:[{ rot:'Crupe (laringite)', mgkg:null, fixa:'2 mg (4 mL de 0,5 mg/mL)', freq:'dose única', conc:null, unid:'mL',
           nota:'Dose fixa, sem cálculo por peso. Alternativa à dexametasona quando a criança vomita.' }],
  atencao:'Não substitui a adrenalina nebulizada no crupe moderado a grave. A dexametasona oral continua sendo a primeira escolha.',
  obs:[] },

{ id:'p-ivermectina', grupo:'antiparasitario', nome:'Ivermectina', apres:'Comprimido 6 mg', via:'VO',
  idade:'A partir de 5 anos e 15 kg (bula)', minMeses:60,
  veto:{ meses:60, txt:'Não usar abaixo de 5 anos ou de 15 kg (bula). Escabiose no lactente: permetrina tópica.' },
  doses:[{ rot:'Dose única (200 mcg/kg)',
           porPeso:[{ min:15, max:24, txt:'½ comprimido (3 mg)', rot:'15 a 24 kg' },
                    { min:24.01, max:35, txt:'1 comprimido (6 mg)', rot:'25 a 35 kg' },
                    { min:35.01, max:50, txt:'1 e ½ comprimido (9 mg)', rot:'36 a 50 kg' },
                    { min:50.01, max:65, txt:'2 comprimidos (12 mg)', rot:'51 a 65 kg' },
                    { min:65.01, max:79, txt:'2 e ½ comprimidos (15 mg)', rot:'66 a 79 kg' },
                    { min:79.01, max:999, txt:'200 mcg/kg (3 comprimidos ou mais)', rot:'80 kg ou mais' }],
           regra:'200 mcg/kg: 15 a 24 kg ½ comprimido · 25 a 35 kg 1 · 36 a 50 kg 1 e ½ · 51 a 65 kg 2',
           fixa:'200 mcg/kg em dose única (comprimido 6 mg)', fora:'Abaixo de 15 kg: não usar',
           freq:'dose única', nota:'Escabiose e pediculose: repetir em 7 a 14 dias. Estrongiloidíase: dose única (alguns esquemas repetem no dia seguinte). Tomar em jejum, com água.' }],
  atencao:'Abaixo de 15 kg ou 5 anos não usar: barreira hematoencefálica imatura.',
  obs:[] },

{ id:'p-nistatina-oral', grupo:'digestivo', nome:'Nistatina suspensão oral', apres:'Suspensão 100.000 UI/mL', via:'VO (bochecho ou aplicar na mucosa)',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Lactente (monilíase oral)', mgkg:null, fixa:'1 a 2 mL (100.000 a 200.000 UI)', freq:'4× ao dia', conc:null, unid:'mL',
           nota:'Metade em cada lado da boca, depois das mamadas. Prematuro e recém-nascido de baixo peso: 1 mL. Manter por 48 h depois de a placa sumir (em geral 7 a 14 dias).' },
         { rot:'Criança maior', mgkg:null, fixa:'4 a 6 mL (400.000 a 600.000 UI)', freq:'4× ao dia', conc:null, unid:'mL',
           nota:'Bochechar e manter na boca o máximo possível antes de engolir.' }],
  atencao:'Trate também o mamilo da mãe e ferva bicos e chupetas, senão a monilíase volta.',
  obs:[] },

{ id:'p-hidroxizina', grupo:'alergia', nome:'Hidroxizina', apres:'Solução oral 2 mg/mL · comprimido 25 mg', via:'VO',
  idade:'A partir de 6 meses (bula)', minMeses:6,
  veto:{ meses:6, txt:'Não indicada abaixo de 6 meses (bula).' },
  doses:[{ rot:'Prurido e urticária', mgkg:0.5, mgkgMax:1, freq:'8/8 h', maxMg:25, conc:2, unid:'mL',
           nota:'0,5 a 1 mg/kg por dose (bula: 0,7 mg/kg = 0,35 mL/kg), máximo de 25 mg por dose. Até 10 dias.' }],
  atencao:'Seda bastante e prolonga o QT. Na anafilaxia é adjuvante: nunca substitui a adrenalina.',
  obs:['Útil à noite no prurido que não deixa dormir; de dia, prefira cetirizina ou loratadina.'] },

{ id:'p-cetirizina', grupo:'alergia', nome:'Cetirizina', apres:'Solução oral 1 mg/mL · comprimido 10 mg', via:'VO',
  idade:'A partir de 2 anos (bula)', minMeses:24,
  veto:{ meses:24, txt:'Não recomendada abaixo de 2 anos (bula).' },
  doses:[{ rot:'Dose por idade',
           porIdade:[{ min:24, max:71, txt:'2,5 mL (2,5 mg) de 12/12 h', rot:'2 a 5 anos' },
                     { min:72, max:143, txt:'5 mL (5 mg) de 12/12 h, ou 10 mL (10 mg) 1 vez ao dia', rot:'6 a 11 anos' },
                     { min:144, max:216, txt:'10 mg (1 comprimido) 1 vez ao dia', rot:'12 anos ou mais' }],
           regra:'2 a 5 anos: 2,5 mg de 12/12 h · 6 a 11 anos: 5 mg de 12/12 h · 12 anos ou mais: 10 mg/dia',
           fixa:'2 a 5 anos: 2,5 mg de 12/12 h · 6 a 11 anos: 5 mg de 12/12 h · 12 anos ou mais: 10 mg/dia',
           fora:'Abaixo de 2 anos: não recomendada', freq:'' }],
  atencao:'Pouco sedativa, mas alguma sonolência acontece. Ajustar na insuficiência renal.',
  obs:['Boa para urticária e rinite alérgica no uso diurno.'] },

{ id:'p-peg', grupo:'digestivo', nome:'Polietilenoglicol 4000 (PEG)', apres:'Pó manipulado ou sachês de 4 g e 10 g', via:'VO',
  idade:'A partir de 6 meses (confira a bula do produto: alguns só acima de 2 anos)', minMeses:6, veto:null,
  doses:[{ rot:'Desimpactação fecal', mgkg:1000, mgkgMax:1500, freq:'1× ao dia por 3 a 6 dias', maxMg:100000, conc:null, unid:'mg',
           nota:'1 a 1,5 g/kg por dia, máximo de 100 g/dia. O valor sai em mg: 1.000 mg = 1 g. Diluir cada 1 g em cerca de 10 mL de água ou suco.' },
         { rot:'Manutenção', mgkg:400, mgkgMax:800, freq:'1× ao dia', maxMg:17000, conc:null, unid:'mg',
           nota:'0,4 a 0,8 g/kg por dia, máximo de 17 g/dia, ajustando até fezes pastosas diárias. Manter por meses e desmamar devagar.' }],
  atencao:'Exclua obstrução (vômito bilioso, distensão, parada de gases) antes de desimpactar.',
  obs:['Laxante de primeira escolha na constipação funcional da criança (NASPGHAN/ESPGHAN).'] },

{ id:'p-sulfato-ferroso', grupo:'digestivo', nome:'Sulfato ferroso', apres:'Gotas 25 mg/mL de ferro elementar (1 gota = 1,25 mg)', via:'VO',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Tratamento da anemia ferropriva', mgkg:3, mgkgMax:6, freq:'1× ao dia, longe do leite', maxMg:120, conc:25, unid:'mL',
           nota:'Valor mostrado = total por dia, em ferro elementar (3 a 6 mg/kg/dia; máximo de 120 mg/dia no adolescente). Pode ser dividido em 2 tomadas se houver dor abdominal. Manter por 2 a 3 meses depois de normalizar a hemoglobina.' }],
  atencao:'A dose é em FERRO ELEMENTAR, não em sal: confira a apresentação. Outras gotas (ferro quelato, polimaltosado) têm outra concentração.',
  obs:['Escurece as fezes e pode manchar os dentes: dar com conta-gotas no fundo da boca e escovar depois.','Reavaliar a hemoglobina em 4 semanas: deve subir pelo menos 1 g/dL.'] },

{ id:'p-vancomicina', grupo:'atb-ev', nome:'Vancomicina', apres:'Frasco-ampola 500 mg e 1 g', via:'EV',
  idade:'Qualquer idade, com ajuste no neonato', minMeses:0, veto:null,
  doses:[{ rot:'Infecção grave, MRSA, meningite', mgkg:15, mgkgMax:15, freq:'6/6 h', maxMg:1000, conc:null, unid:'mg',
           nota:'15 mg/kg por dose, máximo de 1 g por dose (60 mg/kg/dia). Diluir a até 5 mg/mL e infundir em pelo menos 60 minutos. No neonato, intervalo maior conforme a idade gestacional.' }],
  atencao:'Nefrotóxica: ajuste pela função renal e monitore nível sérico (vale ou AUC). Infusão rápida causa a síndrome do homem vermelho.',
  obs:['Indicação: suspeita de MRSA, cateter ou dispositivo, meningite com pneumococo resistente, choque séptico com foco cutâneo.'] },

{ id:'p-salina-3', grupo:'emergencia', nome:'Salina hipertônica 3%', apres:'NaCl 3% (pronta, ou 85 mL de SF 0,9% + 15 mL de NaCl 20%)', via:'EV',
  idade:'Qualquer idade', minMeses:0, veto:null,
  doses:[{ rot:'Hipertensão intracraniana', mgkg:null, fixa:'2,5 a 5 mL/kg', freq:'em 10 a 20 min; pode repetir', conc:null, unid:'mL',
           nota:'Máximo de 250 mL por bolus. Também usada na hiponatremia sintomática grave (convulsão): 2 a 3 mL/kg.' }],
  atencao:'Meta de sódio sérico até 150 a 160 mEq/L na hipertensão intracraniana; dose o sódio a cada 4 a 6 horas.',
  obs:['Pode correr em veia periférica calibrosa por curto período; prefira acesso central para infusão contínua.'] }

];
